trigger:
- main  # o tu rama principal

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'python-app'

steps:
- task: DockerInstaller@0
  displayName: 'Instalar Docker'

- script: |
    echo "Construyendo la imagen Docker..."
    docker build -t $(imageName):$(Build.BuildId) .
  displayName: 'Construir imagen Docker'


