trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: flask-app

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      echo "Construyendo imagen Docker..."
      docker build -t $(imageName) .
    displayName: 'Construir imagen Docker'

  - script: |
      echo "Iniciando contenedor..."
      docker run -d -p 5000:5000 --name flask-container $(imageName)
      echo "Esperando que Flask se inicie..."
      sleep 5

      echo "Haciendo solicitud HTTP para verificar que el contenedor responde..."
      curl --fail http://localhost:5000/

      echo "Solicitud exitosa. Deteniendo contenedor..."
      docker stop flask-container
      docker rm flask-container
    displayName: 'Probar contenedor Flask'
