trigger:
- main  # o tu rama principal

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'python-app'

steps:
- task: DockerInstaller@0
  displayName: 'Instalar Docker'

- script: |
    docker run -d -p 5000:5000 --name prueba-app python-app
    sleep 5
    curl http://localhost:5000 || echo "La app no respondió"
    docker stop prueba-app
    docker rm prueba-app
  displayName: "Verificar ejecución del contenedor"



