trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'ConexionAzurePipelines'
  acrName: 'azureprojectflask'
  acrLoginServer: 'azureprojectflask.azurecr.io'
  imageName: 'fpython'
  clusterName: 'fpython-cluster'
  resourceGroup: 'redess'

steps:
- task: DockerInstaller@0
  displayName: 'Instalar Docker'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Login a ACR..."
      az acr login --name $(acrName)

      echo "Construyendo y subiendo imagen..."
      docker build -t $(acrLoginServer)/$(imageName):latest .
      docker push $(acrLoginServer)/$(imageName):latest

      echo "Obteniendo credenciales de AKS..."
      az aks get-credentials --name $(clusterName) --resource-group $(resourceGroup) --overwrite-existing

      echo "Aplicando deployment..."
      kubectl apply -f deployment.yaml
  displayName: 'Build, Push y Deploy a AKS'
