trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'python-app'

steps:
- task: DockerInstaller@0
  displayName: 'Instalar Docker'

- script: |
    docker build -t $(imageName) .
  displayName: 'Construir imagen Docker'

- script: |
    docker run -d -p 5000:5000 --name prueba-app $(imageName)
    sleep 5
    curl http://localhost:5000 || echo "La app no respondió"
    docker stop prueba-app
    docker rm prueba-app
  displayName: 'Verificar ejecución del contenedor'
